### ISSUE TITLE
Combat skills are not calculated correctly

### ISSUE THREAD

**Issue by korma0815** [charichu/saon#47]
- Lower combat skills are lacking the courage modifier which results in lower values as it should
- High level combat skills shows too high attack values

- Parade values are also lower as they should

![image](https://user-images.githubusercontent.com/37847187/100753736-7a2c0080-33ea-11eb-97f6-45ce43020c0a.png)
![image](https://user-images.githubusercontent.com/37847187/100753774-831cd200-33ea-11eb-812f-3e0fae1b300f.png)

**Comment by korma0815** [comment]
the courage modifier should be floor(((courage)-8)/3);

**Comment by charichu** [comment]
Boniberechnung:

    let combatBonusFF = Math.floor(((character?.coreAttributes?.dexterity - 8) / 3));
    let combatBonusGE = Math.floor(((character?.coreAttributes?.agility - 8) / 3));
    let combatBonusKK = Math.floor(((character?.coreAttributes?.strength - 8) / 3));
    let combatBonusAT = Math.floor(((character?.coreAttributes?.courage - 8) / 3));
    let combatBonusGEKK = (combatBonusGE>combatBonusKK) ? combatBonusGE : combatBonusKK;

Ranged:

     AT: combatBonusFF + (character?.combatTechniques?.Discuses || 6),

Melee:
    AT: combatBonusAT +  (character?.combatTechniques?.Daggers || 6),
    PA: combatBonusGE +  (Math.ceil(character?.combatTechniques?.Daggers/2)  || 3),


I had wrong parentheses for the base value if the skill is undefined, so the boni would not be added. 
The wrong AT values happended because i took the leading attribute and not courage


Also refactored calucation into functions for cleaner changes next time,
Changed weapon and armor function for cleaner code and better typescript as well, also added items to the expose"
