### ISSUE TITLE
Some characters can't be imported

### ISSUE THREAD

**Issue by korma0815** [charichu/saon#64]
Some character uploads results in an error after ~2 minutes

- Warning: file_get_contents(http://www.saon-beta.xyz/api/characters/5fce06d43199be0018534f00): failed to open stream: HTTP request failed! i  -> (Fidelius_IV._Kradolan(4).json)
- Warning: file_get_contents(http://www.saon-beta.xyz/api/characters/5fce07703199be0018534f03): failed to open stream: HTTP request failed! -> Almagan-Interfex .json
- Warning: file_get_contents(http://www.saon-beta.xyz/api/characters/5fce079f3199be0018534f05): failed to open stream: HTTP request failed! -> Al_Saher.json

[failed chars.zip](https://github.com/charichu/saon/files/5652147/failed.chars.zip)

**Comment by charichu** [comment]
Seems to be a problem with special characters in the character name.

Fix coming soon :)

**Comment by charichu** [comment]
Or not. It was the profession name mapping.

I know do a better check during the import. It couldnt find the "custom" profession. Since sometimes Optolith exports with a profession id which will look like this :  "p":"P_21" but custom professions show up with this: "professionName": "\"Händler\"" AND "p": "P_0".

Short test then will be pushed
